### ISSUE TITLE
All the AEP sidebar links lead to a 404

### ISSUE THREAD

**Issue by blaberg** [aep-dev/aep.dev#225]
When browsing the currently deployed website, anytime you try to read one of the AEPs you will be met with the following screen: 

<img width="1474" alt="Skärmavbild 2024-10-16 kl  13 31 05" src="https://github.com/user-attachments/assets/c8913a8d-b4a0-42f4-8c68-3a8f6c7dcca4">

This is because the AEP links are pointing to a `beta`- subdomain (i.e. `https://beta.aep.dev/<aep number>`). When removing the `beta` subdomain the page is displayed as normal.

**Comment by toumorokoshi** [comment]
@blaberg thanks for the report! the links should be fixed now thanks to https://github.com/aep-dev/site-generator-beta/pull/41. I've verified a couple links, but can you try it too?

**Comment by blaberg** [comment]
Yes, everything seems to work as expected now. Thanks for looking in to it!
