### ISSUE TITLE
Update/fork site generator to say "AEP" rather than "AIP"

### ISSUE THREAD

**Issue by rofrankel** [aep-dev/aep.dev#3]
I think we need to fork the site generator, set it up to deploy to pip, and then update the requirements.txt file in this repo to use the forked one.

**Comment by rofrankel** [comment]
Forked repo: https://github.com/aep-dev/site-generator

**Comment by rofrankel** [comment]
Rebranded: https://github.com/aep-dev/site-generator/pull/1

**Comment by toumorokoshi** [comment]
@rofrankel should we call this complete?

**Comment by rofrankel** [comment]
Yep!
