### ISSUE TITLE
Adopt AIP-0191 File and directory structure

### ISSUE THREAD

**Issue by makahmad** [aep-dev/aep.dev#46]

**Comment by toumorokoshi** [comment]
this one is pretty proto-specific: should we put this into a "protobuf" section?

the HTTP transcoding AEP would also fit in this category.

**Comment by rambleraptor** [comment]
I don't think this AEP is strictly necessary. There's a lot of Google-specific guidance in here (why do you need `java_package_name` but not `go_package_name`?) and none of it helps makes the APIs themselves any more intuitive / easy-to-generate.

**Comment by rofrankel** [comment]
@rambleraptor is going to drive discussion of whether we need this one.

**Comment by rambleraptor** [comment]
Closed in #186
